version: '3.1'

services:
    jenkins:
        image: jenkinsci/blueocean
        container_name: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - data:/var/jenkins_home
volumes:
    data: