version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    network_mode: bridge
    ports:
      - "9000:9000"
      - "9443:9443"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: