FROM camunda/camunda-bpm-platform
RUN wget -P /camunda/lib http://nexus.onebusaway.org/nexus/content/repositories/public/com/microsoft/sqlserver/sqljdbc6/4.2/sqljdbc6-4.2.jar
RUN cd /camunda/webapps && rm -rf ROOT camunda-invoice camunda-welcome host-manager manager examples docs
RUN mv /camunda/webapps/camunda /camunda/webapps/ROOT
RUN sed -i 's/name="jobExecutorDeploymentAware">true</name="jobExecutorDeploymentAware">false</g' /camunda/conf/bpm-platform.xml
RUN sed -i 's/<job-acquisition name="default" \/>/<job-acquisition name="default"><properties><property name="maxJobsPerAcquisition">5<\/property><property name="waitTimeInMillis">8000<\/property><property name="lockTimeInMillis">400000<\/property><\/properties><\/job-acquisition><properties><!-- Note: the following properties only take effect in a Tomcat environment --><property name="queueSize">3<\/property><property name="corePoolSize">5<\/property><property name="maxPoolSize">15<\/property><property name="keepAliveTime">0<\/property><\/properties>/g' /camunda/conf/bpm-platform.xml

