FROM fjcj/glpi
RUN wget https://github.com/fusioninventory/fusioninventory-for-glpi/releases/download/glpi9.5.0%2B1.0/fusioninventory-9.5.0+1.0.tar.bz2 -O /var/www/html/plugins/fi.tar.bz2 && \
	cd /var/www/html/plugins/ && tar -xf fi.tar.bz2