# /var/run/docker.sock does not seem to be available for fig
# for this reason we violate LFHS and add the socket directly on /run
dnsdock:
    image: conz27/dnsdock
    container_name: dnsdock
    command: -nameserver 10.0.0.30:53 -nameserver 8.8.8.8:53
    volumes:
        - /var/run/docker.sock:/run/docker.sock
    ports:
        - 53:53/udp
