version: '3.1'

services:
    salt:
        image: bbinet/salt-master
        container_name: salt
        ports:
            - "4505:4505"
            - "4506:4506"
            - "443:443"
        volumes:
            - config:/config
            - data:/data
volumes:
    config:
    data: