version: '3.1'

services:
    rundeck:
        image: camposdelima/rundecksalt
        container_name: rundeck
        hostname: rundeck
        ports:
            - "4440:4440"
        environment:
            SERVER_URL: http://10.0.0.95:4440
            EXTERNAL_SERVER_URL: http://10.0.0.95:4440
        volumes:
            - plugins:/opt/rundeck-plugins
            - data:/var/rundeck
        networks:
            salt:
networks:
    salt:
        external:
          name: salt_default
volumes:
    plugins:
    data: