version: '3.1'

services:
  artifactory:
    image: mattgruter/artifactory
    container_name: artifactory
    ports:
        - "8081:8080"
    volumes:
        - data:/artifactory/data
volumes:
        data:       